[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Allow forge scripts to write deployment artifacts
fs_permissions = [{ access = "write", path = "./deployments" }]

evm_version = "cancun"
optimizer = true
optimizer-runs = 200
solc = "0.8.25"
via_ir = false
